version: 3.8.3

services:
  mysql:
    container_name: mysqldb
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=PetCare'
      - 'MYSQL_PASSWORD=mysql_1789'
      - 'MYSQL_USER=mysql'
      - 'MYSQL_ROOT_PASSWORD=mysql_1789'

    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 20s
      retries: 5

  application:
    container_name: pawbuddies
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE_ACTIVE:-dev}
    restart: on-failure
volumes:
  mysql-data: